
package administradores;

import com.formdev.flatlaf.FlatLightLaf;
import conexion.ConectarBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author alvarogonzalezandrades
 */
public class CrearTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form añadir_empleado
     */
    public CrearTrabajador() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        campoFecha_Ingreso.setText(LocalDate.now().toString());
        campoFecha_Ingreso.setEnabled(false);

   setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        textTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        campoEdad = new javax.swing.JTextField();
        textEdad = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        textNombre = new javax.swing.JLabel();
        textApellidos = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        textFecha_Ingreso = new javax.swing.JLabel();
        campoFecha_Ingreso = new javax.swing.JTextField();
        campoSalario = new javax.swing.JTextField();
        textSalario = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        textDNI = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        textDireccion = new javax.swing.JLabel();
        textUsuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JTextField();
        textContraseña = new javax.swing.JLabel();
        rdDesactivado = new javax.swing.JRadioButton();
        rdActivado = new javax.swing.JRadioButton();
        textEstado = new javax.swing.JLabel();
        comboJornada = new javax.swing.JComboBox<>();
        textJornada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1444, 880));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Añadir trabajador");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 910, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 110));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1430, 20));

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 760, 100, 40));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 100, 40));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 110, 20, 740));

        jPanel3.setBackground(new java.awt.Color(219, 219, 209));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textTipo.setForeground(new java.awt.Color(0, 0, 0));
        textTipo.setText("Tipo");
        jPanel3.add(textTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 40, 30));

        comboTipo.setBackground(java.awt.Color.white);
        comboTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcionista", "Tecnico" }));
        jPanel3.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 190, -1));

        campoEdad.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        textEdad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textEdad.setForeground(new java.awt.Color(0, 0, 0));
        textEdad.setText("Edad");
        jPanel3.add(textEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 60, 30));

        campoNombre.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, -1));

        textNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
        textNombre.setText("Nombre");
        jPanel3.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));

        textApellidos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textApellidos.setForeground(new java.awt.Color(0, 0, 0));
        textApellidos.setText("Apellidos");
        jPanel3.add(textApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));

        campoApellidos.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 210, -1));

        textFecha_Ingreso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textFecha_Ingreso.setForeground(new java.awt.Color(0, 0, 0));
        textFecha_Ingreso.setText("Fecha Ingreso");
        jPanel3.add(textFecha_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 100, 30));

        campoFecha_Ingreso.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoFecha_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 210, -1));

        campoSalario.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 200, -1));

        textSalario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textSalario.setForeground(new java.awt.Color(0, 0, 0));
        textSalario.setText("Salario");
        jPanel3.add(textSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 80, 30));

        campoDNI.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 200, -1));

        textDNI.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textDNI.setForeground(new java.awt.Color(0, 0, 0));
        textDNI.setText("DNI");
        jPanel3.add(textDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 70, 30));

        campoDireccion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 220, -1));

        textDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 0, 0));
        textDireccion.setText("Dirección");
        jPanel3.add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 100, 30));

        textUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textUsuario.setText("Usuario");
        jPanel3.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 90, 30));

        campoUsuario.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 200, -1));

        campoContraseña.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jPanel3.add(campoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 220, -1));

        textContraseña.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textContraseña.setForeground(new java.awt.Color(0, 0, 0));
        textContraseña.setText("Contraseña");
        jPanel3.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 100, 30));

        btnGroupEstado.add(rdDesactivado);
        rdDesactivado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rdDesactivado.setForeground(new java.awt.Color(0, 0, 0));
        rdDesactivado.setText("Desactivado");
        rdDesactivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDesactivadoActionPerformed(evt);
            }
        });
        jPanel3.add(rdDesactivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, 30));

        btnGroupEstado.add(rdActivado);
        rdActivado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rdActivado.setForeground(new java.awt.Color(0, 0, 0));
        rdActivado.setText("Activado");
        rdActivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActivadoActionPerformed(evt);
            }
        });
        jPanel3.add(rdActivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, 30));

        textEstado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textEstado.setForeground(new java.awt.Color(0, 0, 0));
        textEstado.setText("Estado:");
        jPanel3.add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 60, 30));

        comboJornada.setBackground(java.awt.Color.white);
        comboJornada.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completa", "Media" }));
        comboJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJornadaActionPerformed(evt);
            }
        });
        jPanel3.add(comboJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, -1));

        textJornada.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textJornada.setForeground(new java.awt.Color(0, 0, 0));
        textJornada.setText("Jornada");
        jPanel3.add(textJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 70, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1320, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJornadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJornadaActionPerformed

    private void rdDesactivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDesactivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDesactivadoActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        String texto = campoUsuario.getText();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellene el campo.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        } else {

        }
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void rdActivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdActivadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        String textoDNI = campoDNI.getText();
        int age = Integer.parseInt(campoEdad.getText());

        if (campoNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena el nombre.", "Campo Nombre", JOptionPane.WARNING_MESSAGE);
        } else if (campoApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena los apellidos.", "Campo Apellidos", JOptionPane.WARNING_MESSAGE);
        } else if (campoEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena la edad", "Campo Edad", JOptionPane.WARNING_MESSAGE);
        } else if (textoDNI.length() != 9) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese exactamente 9 caracteres en el dni", "Error", JOptionPane.WARNING_MESSAGE);

        } else {

            if (age < 18 || age > 65) {
                JOptionPane.showMessageDialog(this, "Edad no apta. Debe estar entre 18 y 65.", "Campo Edad", JOptionPane.WARNING_MESSAGE);
            }

            if (campoUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, rellena el nombre usuario.", "Campo Nombre usuario", JOptionPane.WARNING_MESSAGE);
            } else if (campoContraseña.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, rellena los contraseña.", "Campo Contraseña", JOptionPane.WARNING_MESSAGE);
            } else if (campoDireccion.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, rellena la dirección.", "Campo email", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Se ha registrado correctamente el usuario en la base de datos", "Registro con exito", JOptionPane.WARNING_MESSAGE);

            }

            Connection cn = ConectarBD.conectar();

            nombre = campoNombre.getText();
            apellidos = campoApellidos.getText();
            dni = campoDNI.getText();
            edad = Integer.parseInt(campoEdad.getText());
            usuario = campoUsuario.getText();
            contraseña = campoContraseña.getText().toString();
            direccion = campoDireccion.getText();
            salario = Float.parseFloat(campoSalario.getText());

            if (comboTipo.getSelectedItem().toString().equals("Administrador")) {
                tipo = "Administrador";
            }
            if (comboTipo.getSelectedItem().toString().equals("Recepcionista")) {
                tipo = "Recepcionista";
            }
            if (comboTipo.getSelectedItem().toString().equals("Técnicos")) {
                tipo = "Técnicos";
            }

            if (comboJornada.getSelectedItem().toString().equals("Completa")) {
                jornada = "Completa";
            }
            if (comboJornada.getSelectedItem().toString().equals("Media")) {
                jornada = "Media";
            }
            
            if(rdActivado.isSelected()) estado="Activo";
            else if(rdDesactivado.isSelected()) estado="Inactivo";

            try {
                String consulta = "INSERT INTO TRABAJADORES (DNI, Usuario, Pass, Nombre, Apellidos, Edad, FechaIngreso, TipoJornada, Salario, EstadoActual, Tipo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = cn.prepareStatement(consulta);

                ps.setString(1, dni);
                ps.setString(2, usuario);
                ps.setString(3, contraseña);
                ps.setString(4, nombre);
                ps.setString(5, apellidos);
                ps.setInt(6, edad);
                ps.setString(7, LocalDate.now().toString());
                ps.setString(8, jornada);
                ps.setFloat(9, salario);
                ps.setString(10, estado);
                ps.setString(11, tipo);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Trabajador creado con exito");
                PanelAdminAdministracion paa = new PanelAdminAdministracion();
                paa.setVisible(true);
                this.dispose();

                //IR AL MENU PRINCIPAL
                cn.close();
            } catch (SQLException e) {
                System.err.println("Error en la creacion del trabajador" + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
        PanelTrabajadores panelT = new PanelTrabajadores();
        panelT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 FlatLightLaf.setup();
                new CrearTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupEstado;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoContraseña;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoFecha_Ingreso;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboJornada;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdActivado;
    private javax.swing.JRadioButton rdDesactivado;
    private javax.swing.JLabel textApellidos;
    private javax.swing.JLabel textContraseña;
    private javax.swing.JLabel textDNI;
    private javax.swing.JLabel textDireccion;
    private javax.swing.JLabel textEdad;
    private javax.swing.JLabel textEstado;
    private javax.swing.JLabel textFecha_Ingreso;
    private javax.swing.JLabel textJornada;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textSalario;
    private javax.swing.JLabel textTipo;
    private javax.swing.JLabel textUsuario;
    // End of variables declaration//GEN-END:variables
       String dni;
    String nombre;
    String apellidos;
    int edad;
    String direccion;
    String fechaIngreso;
    String jornada;
    float salario;
    String tipo;
    String estado;
    int horasTrabajadas;
    String usuario;
    String contraseña;
    String idSeleccionado;

}
