/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administradores;

import com.formdev.flatlaf.FlatLightLaf;
import conexion.ConectarBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author javier
 */
public class ModificarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public ModificarTrabajador() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        Connection cn = ConectarBD.conectar();
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM TRABAJADORES WHERE ID_TRABAJADORES = ?");
            ps.setString(1, ConsultarTrabajador.idSeleccionado);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                campoDNI.setText(rs.getString(2));
                campoUsuario.setText(rs.getString(3));
                campoContraseña.setText(rs.getString(4));
                campoNombre.setText(rs.getString(5));
                campoApellido.setText(rs.getString(6));
                campoEdad.setText(rs.getString(7));
                campoFechaIngreso.setText(rs.getString(8));
                jornada = rs.getString(9);
                campoSalario.setText(rs.getString(10));
                estado = rs.getString(11);
                tipo = rs.getString(12);

            }
            
            if (jornada.equals("Completa")) {
                comboBoxJornada.setSelectedIndex(0);
            } else {
                comboBoxJornada.setSelectedIndex(1);
            }

            if (tipo.equals("Administrador")) {
                comboBoxTipo.setSelectedIndex(0);
            } else if (tipo.equals("Recepcionista")) {
                comboBoxTipo.setSelectedIndex(1);
            } else {
                comboBoxTipo.setSelectedIndex(2);
            }

            if (estado.equals("Activo")) {
                rbActivado.setSelected(true);
            } else {
                rbDesactivado.setSelected(true);
            }

        } catch (SQLException e) {
            System.err.println("Error en la muestra de los datos " + e.getMessage());
        }
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        campoContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        comboBoxTipo = new javax.swing.JComboBox<>();
        rbActivado = new javax.swing.JRadioButton();
        textUsuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        textNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        textContrasena = new javax.swing.JLabel();
        textApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        textDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        textSalario = new javax.swing.JLabel();
        textFechaIngreso = new javax.swing.JLabel();
        campoFechaIngreso = new javax.swing.JTextField();
        textEdad = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        campoSalario = new javax.swing.JTextField();
        textTipo = new javax.swing.JLabel();
        comboBoxJornada = new javax.swing.JComboBox<>();
        textIBAN = new javax.swing.JLabel();
        textEstado = new javax.swing.JLabel();
        rbDesactivado = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        textModificacion = new javax.swing.JLabel();
        chModificar = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        campoContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoContraseña.setEnabled(false);
        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(campoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 240, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1430, 10));

        comboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxTipo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcionista", "Tecnico" }));
        comboBoxTipo.setEnabled(false);
        jPanel1.add(comboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 230, 30));

        buttonGroup2.add(rbActivado);
        rbActivado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rbActivado.setForeground(new java.awt.Color(0, 0, 0));
        rbActivado.setText("Activado");
        rbActivado.setEnabled(false);
        jPanel1.add(rbActivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, 120, 50));

        textUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textUsuario.setText("Usuario:");
        jPanel1.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 139, -1, 30));

        campoUsuario.setEditable(false);
        campoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoUsuario.setEnabled(false);
        jPanel1.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 250, -1));

        textNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
        textNombre.setText("Nombre:");
        jPanel1.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 59, 80, 30));

        campoNombre.setBackground(new java.awt.Color(255, 255, 255));
        campoNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoNombre.setEnabled(false);
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 250, -1));

        textContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textContrasena.setForeground(new java.awt.Color(0, 0, 0));
        textContrasena.setText("Contraseña:");
        jPanel1.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 139, -1, 30));

        textApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textApellido.setForeground(new java.awt.Color(0, 0, 0));
        textApellido.setText("Apellido:");
        jPanel1.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 30));

        campoApellido.setBackground(new java.awt.Color(255, 255, 255));
        campoApellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoApellido.setEnabled(false);
        jPanel1.add(campoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 240, -1));

        textDNI.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textDNI.setForeground(new java.awt.Color(0, 0, 0));
        textDNI.setText("DNI:");
        jPanel1.add(textDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 60, 30));

        campoDNI.setBackground(new java.awt.Color(255, 255, 255));
        campoDNI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoDNI.setEnabled(false);
        jPanel1.add(campoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 240, -1));

        textSalario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textSalario.setForeground(new java.awt.Color(0, 0, 0));
        textSalario.setText("Salario:");
        jPanel1.add(textSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 139, 110, 30));

        textFechaIngreso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textFechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        textFechaIngreso.setText("Fecha de ingreso:");
        jPanel1.add(textFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, 30));

        campoFechaIngreso.setEditable(false);
        campoFechaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        campoFechaIngreso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoFechaIngreso.setEnabled(false);
        jPanel1.add(campoFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 250, -1));

        textEdad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textEdad.setForeground(new java.awt.Color(0, 0, 0));
        textEdad.setText("Edad:");
        jPanel1.add(textEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        campoEdad.setBackground(new java.awt.Color(255, 255, 255));
        campoEdad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoEdad.setEnabled(false);
        jPanel1.add(campoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        campoSalario.setBackground(new java.awt.Color(255, 255, 255));
        campoSalario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoSalario.setEnabled(false);
        jPanel1.add(campoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 250, -1));

        textTipo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textTipo.setForeground(new java.awt.Color(0, 0, 0));
        textTipo.setText("Tipo:");
        jPanel1.add(textTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 30));

        comboBoxJornada.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxJornada.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboBoxJornada.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completa", "Media" }));
        comboBoxJornada.setEnabled(false);
        jPanel1.add(comboBoxJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 260, 30));

        textIBAN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textIBAN.setForeground(new java.awt.Color(0, 0, 0));
        textIBAN.setText("Jornada:");
        jPanel1.add(textIBAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 219, 120, 30));

        textEstado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textEstado.setForeground(new java.awt.Color(0, 0, 0));
        textEstado.setText("Estado actual:");
        jPanel1.add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, 30));

        buttonGroup2.add(rbDesactivado);
        rbDesactivado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rbDesactivado.setForeground(new java.awt.Color(0, 0, 0));
        rbDesactivado.setText("Desactivado");
        rbDesactivado.setEnabled(false);
        rbDesactivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesactivadoActionPerformed(evt);
            }
        });
        jPanel1.add(rbDesactivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 120, 50));

        jPanel2.setBackground(new java.awt.Color(219, 219, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textModificacion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textModificacion.setForeground(new java.awt.Color(0, 0, 0));
        textModificacion.setText("Modificar");
        jPanel2.add(textModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 330, 70, -1));

        chModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chModificarActionPerformed(evt);
            }
        });
        jPanel2.add(chModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 330, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1350, 360));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 20, 580));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 30));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 520, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDesactivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesactivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDesactivadoActionPerformed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void chModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chModificarActionPerformed
        // TODO add your handling code here:
        if(chModificar.isSelected()){
            campoUsuario.setEnabled(true);
            campoContraseña.setEnabled(true);
            campoNombre.setEnabled(true);
            campoApellido.setEnabled(true);
            campoEdad.setEnabled(true);
            campoFechaIngreso.setEnabled(true);
            campoSalario.setEnabled(true);
            comboBoxTipo.setEnabled(true);
            comboBoxJornada.setEnabled(true);
            rbActivado.setEnabled(true);
            rbDesactivado.setEnabled(true);
        }
        if(!chModificar.isSelected()){
            campoUsuario.setEnabled(false);
            campoContraseña.setEnabled(false);
            campoNombre.setEnabled(false);
            campoApellido.setEnabled(false);
            campoEdad.setEnabled(false);
            campoFechaIngreso.setEnabled(false);
            campoSalario.setEnabled(false);
            comboBoxTipo.setEnabled(false);
            comboBoxJornada.setEnabled(false);
            rbActivado.setEnabled(false);
            rbDesactivado.setEnabled(false);
        }
    }//GEN-LAST:event_chModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
        this.dispose();
        ConsultarTrabajador conT = new ConsultarTrabajador();
        conT.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // TODO add your handling code here:

        if (rbActivado.isSelected()) {
            estado = "Activo";
        }
        if (rbDesactivado.isSelected()) {
            estado = "Inactivo";
        }

        // Convertir el arreglo de caracteres a String correctamente
        String contraseña = new String(campoContraseña.getPassword());

        try {
            Connection cn = ConectarBD.conectar();
            String consulta = "UPDATE TRABAJADORES SET Usuario = ?, Pass = ?, Nombre = ?, Apellidos = ?, Edad = ?, FechaIngreso = ?, TipoJornada = ?, Salario = ?, EstadoActual = ?, Tipo = ? WHERE DNI = ?";
            PreparedStatement ps = cn.prepareStatement(consulta);

            ps.setString(1, campoUsuario.getText());
            ps.setString(2, contraseña);
            ps.setString(3, campoNombre.getText());
            ps.setString(4, campoApellido.getText());
            ps.setString(5, campoEdad.getText());
            ps.setString(6, campoFechaIngreso.getText());
            ps.setString(7, comboBoxJornada.getSelectedItem().toString());
            ps.setString(8, campoSalario.getText());
            ps.setString(9, estado);
            ps.setString(10, comboBoxTipo.getSelectedItem().toString());
            ps.setString(11, campoDNI.getText());

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Trabajador actualizado con éxito");
            ConsultarTrabajador ct = new ConsultarTrabajador();
            ct.setVisible(true);
            this.dispose();
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en la actualización del trabajador: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 FlatLightLaf.setup();
                new ModificarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoFechaIngreso;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JCheckBox chModificar;
    private javax.swing.JComboBox<String> comboBoxJornada;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbActivado;
    private javax.swing.JRadioButton rbDesactivado;
    private javax.swing.JLabel textApellido;
    private javax.swing.JLabel textContrasena;
    private javax.swing.JLabel textDNI;
    private javax.swing.JLabel textEdad;
    private javax.swing.JLabel textEstado;
    private javax.swing.JLabel textFechaIngreso;
    private javax.swing.JLabel textIBAN;
    private javax.swing.JLabel textModificacion;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textSalario;
    private javax.swing.JLabel textTipo;
    private javax.swing.JLabel textUsuario;
    // End of variables declaration//GEN-END:variables
    String dni;
    String nombre;
    String apellidos;
    int edad;
    String email;
    String fechaIngreso;
    String jornada;
    float salario;
    String tipo;
    String estado;
    int horasTrabajadas;
    String usuario;
    String contraseña;
    String idSeleccionado;
    String consulta;

}
