/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administradores;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author QQT
 */
public class PanelAdminAdministracion extends JFrame {

    /**
     * Creates new form PanelAdminAdministracion
     */
    public PanelAdminAdministracion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        labelbacktrabajadores.setVisible(false);
        labelbackestadisticas.setVisible(false);

        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                actualizarHora();
            }
        });
        timer.start();
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    private void actualizarHora() {
        Locale spanish = new Locale("es", "ES");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendario = Calendar.getInstance();
        int hora, minutos, segundos;
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);

        labelhora.setText(sdf.format(new java.util.Date()) + "  " + hora + ":" + minutos + ":" + segundos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnVolverAtras = new javax.swing.JButton();
        txtEstadisticas = new javax.swing.JLabel();
        txtVolverAtras = new javax.swing.JLabel();
        btnTrabajadores = new javax.swing.JButton();
        txtTrabajadores = new javax.swing.JLabel();
        btnEstadísticas = new javax.swing.JButton();
        labelbackestadisticas = new javax.swing.JLabel();
        labelbacktrabajadores = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelhora1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Panel de control administracion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 460, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 110));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1430, 20));

        btnVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconatras.png"))); // NOI18N
        btnVolverAtras.setBorder(null);
        btnVolverAtras.setBorderPainted(false);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 90, 80));

        txtEstadisticas.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEstadisticas.setText("Estadísticas");
        jPanel1.add(txtEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 290, 120, 30));

        txtVolverAtras.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtVolverAtras.setText("Volver atrás");
        jPanel1.add(txtVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 780, -1, 40));

        btnTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgTrabajadorPrincipal.png"))); // NOI18N
        btnTrabajadores.setBorder(null);
        btnTrabajadores.setBorderPainted(false);
        btnTrabajadores.setContentAreaFilled(false);
        btnTrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrabajadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrabajadoresMouseExited(evt);
            }
        });
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 130, -1));

        txtTrabajadores.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTrabajadores.setText("Trabajadores");
        jPanel1.add(txtTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, 30));

        btnEstadísticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgEstadistica.png"))); // NOI18N
        btnEstadísticas.setBorder(null);
        btnEstadísticas.setBorderPainted(false);
        btnEstadísticas.setContentAreaFilled(false);
        btnEstadísticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEstadísticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadísticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstadísticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstadísticasMouseExited(evt);
            }
        });
        jPanel1.add(btnEstadísticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 130, 150));

        labelbackestadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackestadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackestadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackestadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackestadisticasMouseExited(evt);
            }
        });
        jPanel1.add(labelbackestadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 220, 200));

        labelbacktrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbacktrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbacktrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbacktrabajadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbacktrabajadoresMouseExited(evt);
            }
        });
        jPanel1.add(labelbacktrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 210, 200));

        labelhora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 770, 210, 60));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 110, 20, 740));

        labelhora1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labelhora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 770, 220, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        PanelTrabajadores pt = new PanelTrabajadores();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        PanelPrincipalAdmin ppa = new PanelPrincipalAdmin();
        ppa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void labelbackestadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackestadisticasMouseEntered

    }//GEN-LAST:event_labelbackestadisticasMouseEntered

    private void labelbackestadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackestadisticasMouseExited

    }//GEN-LAST:event_labelbackestadisticasMouseExited

    private void labelbacktrabajadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajadoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajadoresMouseEntered

    private void labelbacktrabajadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajadoresMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajadoresMouseExited

    private void btnTrabajadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadoresMouseEntered
        labelbacktrabajadores.setVisible(true);

    }//GEN-LAST:event_btnTrabajadoresMouseEntered

    private void btnTrabajadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadoresMouseExited
        labelbacktrabajadores.setVisible(false);

    }//GEN-LAST:event_btnTrabajadoresMouseExited

    private void btnEstadísticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadísticasMouseEntered
        labelbackestadisticas.setVisible(true);

    }//GEN-LAST:event_btnEstadísticasMouseEntered

    private void btnEstadísticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadísticasMouseExited
        labelbackestadisticas.setVisible(false);

    }//GEN-LAST:event_btnEstadísticasMouseExited

    private void btnEstadísticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadísticasMouseClicked
        PanelEstadisticas esta = new PanelEstadisticas();
        esta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstadísticasMouseClicked
    String rutaIconRojo = "/iconimages/iconcerrarsesion.png";
    ImageIcon iconorojo = new ImageIcon(getClass().getResource(rutaIconRojo));

    String rutaIconNegro = "/iconimages/iconcerrarsesioninactivo.png";
    ImageIcon icononegro = new ImageIcon(getClass().getResource(rutaIconNegro));

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdminAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdminAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdminAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdminAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                new PanelAdminAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadísticas;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelbackestadisticas;
    private javax.swing.JLabel labelbacktrabajadores;
    private javax.swing.JLabel labelhora;
    private javax.swing.JLabel labelhora1;
    private javax.swing.JLabel txtEstadisticas;
    private javax.swing.JLabel txtTrabajadores;
    private javax.swing.JLabel txtVolverAtras;
    // End of variables declaration//GEN-END:variables
}
