
package administradores;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author QQT
 */
public class PanelTrabajadores extends JFrame {

    /**
     * Creates new form FrameTrabajadores
     */
    public PanelTrabajadores() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        labelbacktrabaja.setVisible(false);
        labelbacktrabajadoresconsu.setVisible(false);

        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                actualizarHora();
            }
        });
        timer.start();
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    private void actualizarHora() {
        Locale spanish = new Locale("es", "ES");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendario = Calendar.getInstance();
        int hora, minutos, segundos;
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);

        labelhora.setText(sdf.format(new java.util.Date()) + "  " + hora + ":" + minutos + ":" + segundos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAnadirTrabajador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        txtVolverAtras = new javax.swing.JLabel();
        txtConsultarTrabajador = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelbacktrabajadoresconsu = new javax.swing.JLabel();
        labelbacktrabaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Paneles trabajador");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 910, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 110));

        txtAnadirTrabajador.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtAnadirTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnadirTrabajador.setText("Añadir trabajador");
        jPanel1.add(txtAnadirTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 214, 170, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgTrabajadorPrincipal.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, 140));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1250, 40));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, 30, 530));

        btnVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconatras.png"))); // NOI18N
        btnVolverAtras.setBorder(null);
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolverAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseClicked(evt);
            }
        });
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, 80));

        txtVolverAtras.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtVolverAtras.setText("Volver atrás");
        jPanel1.add(txtVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, 40));

        txtConsultarTrabajador.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtConsultarTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConsultarTrabajador.setText("Consultar trabajador");
        jPanel1.add(txtConsultarTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 214, 190, 40));

        labelhora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 220, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconconsultarcliente.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 150, 120));

        labelbacktrabajadoresconsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbacktrabajadoresconsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbacktrabajadoresconsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbacktrabajadoresconsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbacktrabajadoresconsuMouseExited(evt);
            }
        });
        jPanel1.add(labelbacktrabajadoresconsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 220, 200));

        labelbacktrabaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbacktrabaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbacktrabaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbacktrabajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbacktrabajaMouseExited(evt);
            }
        });
        jPanel1.add(labelbacktrabaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 210, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CrearTrabajador crearT = new CrearTrabajador();
        this.dispose();
        crearT.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        PanelPrincipalAdmin ppa = new PanelPrincipalAdmin();
        ppa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void labelbacktrabajadoresconsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajadoresconsuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajadoresconsuMouseEntered

    private void labelbacktrabajadoresconsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajadoresconsuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajadoresconsuMouseExited

    private void labelbacktrabajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajaMouseEntered

    private void labelbacktrabajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktrabajaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacktrabajaMouseExited

    private void btnVolverAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseClicked
         PanelAdminAdministracion m = new PanelAdminAdministracion();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverAtrasMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       // TODO add your handling code here:
        ConsultarTrabajador consultar = new ConsultarTrabajador();
        consultar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  FlatLightLaf.setup();
                new PanelTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelbacktrabaja;
    private javax.swing.JLabel labelbacktrabajadoresconsu;
    private javax.swing.JLabel labelhora;
    private javax.swing.JLabel txtAnadirTrabajador;
    private javax.swing.JLabel txtConsultarTrabajador;
    private javax.swing.JLabel txtVolverAtras;
    // End of variables declaration//GEN-END:variables
}
