
package administradores;

import com.formdev.flatlaf.FlatLightLaf;
import inicializar.InicioSesion;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import recepcionistas.Menu1;
import tecnicos.MenuTecnicos;

/**
 *
 * @author QQT
 */
public class PanelPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipalAdmin
     */
    public PanelPrincipalAdmin() {
        initComponents();
        setTitle("Panel principal");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        labelbackadministracion.setVisible(false);
         labelbacktecnicos.setVisible(false);
          labelbackrecepcionistas.setVisible(false);
    
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                actualizarHora();
            }
        });
        timer.start();
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    private void actualizarHora() {
        Locale spanish = new Locale("es", "ES");

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendario = Calendar.getInstance();
        int hora, minutos, segundos;
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);

        labelhora.setText(sdf.format(new java.util.Date()) + "  " + hora + ":" + minutos + ":" + segundos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelcerrar = new javax.swing.JLabel();
        labeltextcerrar = new javax.swing.JLabel();
        txtAdministracion = new javax.swing.JLabel();
        btnAdministracion = new javax.swing.JButton();
        btnTecnicos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRecepcionistas = new javax.swing.JLabel();
        btnRecepcionistas = new javax.swing.JButton();
        txtTecnicos = new javax.swing.JLabel();
        labelbackrecepcionistas = new javax.swing.JLabel();
        labelbackadministracion = new javax.swing.JLabel();
        labelbacktecnicos = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Panel principal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 460, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 110));

        labelcerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconcerrarsesioninactivo.png"))); // NOI18N
        labelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelcerrarMouseExited(evt);
            }
        });
        jPanel1.add(labelcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 70, 80));

        labeltextcerrar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labeltextcerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltextcerrar.setText("Cerrar Sesión");
        jPanel1.add(labeltextcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 770, 110, 60));

        txtAdministracion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtAdministracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdministracion.setText("Administración");
        jPanel1.add(txtAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 50));

        btnAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgTrabajador.png"))); // NOI18N
        btnAdministracion.setBorder(null);
        btnAdministracion.setBorderPainted(false);
        btnAdministracion.setContentAreaFilled(false);
        btnAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdministracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdministracionMouseExited(evt);
            }
        });
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 170, 160));

        btnTecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgTecnico.png"))); // NOI18N
        btnTecnicos.setBorder(null);
        btnTecnicos.setBorderPainted(false);
        btnTecnicos.setContentAreaFilled(false);
        btnTecnicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTecnicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTecnicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTecnicosMouseExited(evt);
            }
        });
        btnTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecnicosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 350, 150, 150));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 110, 20, 740));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1430, 10));

        txtRecepcionistas.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtRecepcionistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecepcionistas.setText("Recepcionistas");
        jPanel1.add(txtRecepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, 40));

        btnRecepcionistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgRecepcion.png"))); // NOI18N
        btnRecepcionistas.setBorder(null);
        btnRecepcionistas.setBorderPainted(false);
        btnRecepcionistas.setContentAreaFilled(false);
        btnRecepcionistas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRecepcionistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecepcionistasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecepcionistasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecepcionistasMouseExited(evt);
            }
        });
        btnRecepcionistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionistasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 150, -1));

        txtTecnicos.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTecnicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTecnicos.setText("Técnicos");
        jPanel1.add(txtTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 294, 100, 40));

        labelbackrecepcionistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackrecepcionistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackrecepcionistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackrecepcionistasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackrecepcionistasMouseExited(evt);
            }
        });
        jPanel1.add(labelbackrecepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 210, 200));

        labelbackadministracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackadministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackadministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackadministracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackadministracionMouseExited(evt);
            }
        });
        jPanel1.add(labelbackadministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 210, 200));

        labelbacktecnicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbacktecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbacktecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbacktecnicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbacktecnicosMouseExited(evt);
            }
        });
        jPanel1.add(labelbacktecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 210, 200));

        labelhora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 770, 220, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecepcionistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecepcionistasActionPerformed

    private void btnTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTecnicosActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        PanelAdminAdministracion paa = new PanelAdminAdministracion();
        paa.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void labelcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarMouseEntered
        labelcerrar.setIcon(iconorojo);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelcerrar.repaint();
    }//GEN-LAST:event_labelcerrarMouseEntered

    private void labelcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarMouseExited
        labelcerrar.setIcon(icononegro);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelcerrar.repaint();
    }//GEN-LAST:event_labelcerrarMouseExited

    private void labelbackrecepcionistasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackrecepcionistasMouseEntered
    
    }//GEN-LAST:event_labelbackrecepcionistasMouseEntered

    private void labelbackrecepcionistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackrecepcionistasMouseExited
   
    }//GEN-LAST:event_labelbackrecepcionistasMouseExited

    private void labelbackadministracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackadministracionMouseEntered
     
    }//GEN-LAST:event_labelbackadministracionMouseEntered

    private void labelbackadministracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackadministracionMouseExited
   
    }//GEN-LAST:event_labelbackadministracionMouseExited

    private void labelbacktecnicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktecnicosMouseEntered
   
    }//GEN-LAST:event_labelbacktecnicosMouseEntered

    private void labelbacktecnicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacktecnicosMouseExited
      
    }//GEN-LAST:event_labelbacktecnicosMouseExited

    private void btnAdministracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministracionMouseEntered
 labelbackadministracion.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));      
    }//GEN-LAST:event_btnAdministracionMouseEntered

    private void btnAdministracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministracionMouseExited
  labelbackadministracion.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));    
    }//GEN-LAST:event_btnAdministracionMouseExited

    private void btnTecnicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTecnicosMouseEntered
          labelbacktecnicos.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnTecnicosMouseEntered

    private void btnTecnicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTecnicosMouseExited
       labelbacktecnicos.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnTecnicosMouseExited

    private void btnRecepcionistasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionistasMouseEntered
       labelbackrecepcionistas.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRecepcionistasMouseEntered

    private void btnRecepcionistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionistasMouseExited
        labelbackrecepcionistas.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRecepcionistasMouseExited

    private void btnTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTecnicosMouseClicked
     MenuTecnicos tec = new MenuTecnicos();
     this.dispose();
     tec.setVisible(true);
   
    }//GEN-LAST:event_btnTecnicosMouseClicked

    private void btnRecepcionistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionistasMouseClicked
       Menu1 men = new Menu1();
       this.dispose();
       men.setVisible(true);
      
    }//GEN-LAST:event_btnRecepcionistasMouseClicked

    private void labelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarMouseClicked
        InicioSesion is = new InicioSesion();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_labelcerrarMouseClicked

     String rutaIconRojo = "/iconimages/iconcerrarsesion.png";
    ImageIcon iconorojo = new ImageIcon(getClass().getResource(rutaIconRojo));
    
    String rutaIconNegro = "/iconimages/iconcerrarsesioninactivo.png";
    ImageIcon icononegro = new ImageIcon(getClass().getResource(rutaIconNegro));
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  FlatLightLaf.setup();
                new PanelPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnRecepcionistas;
    private javax.swing.JButton btnTecnicos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelbackadministracion;
    private javax.swing.JLabel labelbackrecepcionistas;
    private javax.swing.JLabel labelbacktecnicos;
    private javax.swing.JLabel labelcerrar;
    private javax.swing.JLabel labelhora;
    private javax.swing.JLabel labeltextcerrar;
    private javax.swing.JLabel txtAdministracion;
    private javax.swing.JLabel txtRecepcionistas;
    private javax.swing.JLabel txtTecnicos;
    // End of variables declaration//GEN-END:variables
}
