/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administradores;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Hugo
 */
public class PanelEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form PanelEstadísticas
     */
    public PanelEstadisticas() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        labelbackclientela.setVisible(false);
         labelbackproductos.setVisible(false);
          labelbackincidencias.setVisible(false);
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTrabajadores = new javax.swing.JLabel();
        txtIncidencias = new javax.swing.JLabel();
        txtProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        btnVolverAtras = new javax.swing.JButton();
        txtVolverAtras = new javax.swing.JLabel();
        labelbackclientela = new javax.swing.JLabel();
        labelbackproductos = new javax.swing.JLabel();
        labelbackincidencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTrabajadores.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtTrabajadores.setText("Clientela");
        jPanel1.add(txtTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 80, 30));

        txtIncidencias.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtIncidencias.setText("Incidencias");
        jPanel1.add(txtIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 254, -1, 40));

        txtProductos.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtProductos.setText("Productos");
        jPanel1.add(txtProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 254, -1, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/imgTrabajadorPrincipal.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, 130));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/producto.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 150, 150));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/incidente.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 160, 130));

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Panel de estadisticas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 460, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 110));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 110, 30, 660));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1380, 20));

        btnVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconatras.png"))); // NOI18N
        btnVolverAtras.setContentAreaFilled(false);
        btnVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolverAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseExited(evt);
            }
        });
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 90, 80));

        txtVolverAtras.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtVolverAtras.setText("Volver atrás");
        jPanel1.add(txtVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, 40));

        labelbackclientela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackclientela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackclientela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackclientelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackclientelaMouseExited(evt);
            }
        });
        jPanel1.add(labelbackclientela, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, 200));

        labelbackproductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackproductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackproductosMouseExited(evt);
            }
        });
        jPanel1.add(labelbackproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 210, 200));

        labelbackincidencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackincidencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackincidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackincidenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackincidenciasMouseExited(evt);
            }
        });
        jPanel1.add(labelbackincidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 220, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
       
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnVolverAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseClicked
        PanelAdminAdministracion ppa = new PanelAdminAdministracion();
        ppa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasMouseClicked

    private void labelbackclientelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackclientelaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackclientelaMouseEntered

    private void labelbackclientelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackclientelaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackclientelaMouseExited

    private void labelbackproductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackproductosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackproductosMouseEntered

    private void labelbackproductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackproductosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackproductosMouseExited

    private void labelbackincidenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackincidenciasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackincidenciasMouseEntered

    private void labelbackincidenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackincidenciasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackincidenciasMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        labelbackclientela.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        labelbackclientela.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       labelbackproductos.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        labelbackproductos.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       labelbackincidencias.setVisible(true);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
         labelbackincidencias.setVisible(false);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel3MouseExited

    private void btnVolverAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseEntered
      setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnVolverAtrasMouseEntered

    private void btnVolverAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseExited
     setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnVolverAtrasMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        EstadisticasClientela ec = new EstadisticasClientela();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        EstadisticasProductos ep = new EstadisticasProductos();
        ep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        EstadisticasIncidencias ei = new EstadisticasIncidencias();
        ei.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelbackclientela;
    private javax.swing.JLabel labelbackincidencias;
    private javax.swing.JLabel labelbackproductos;
    private javax.swing.JLabel txtIncidencias;
    private javax.swing.JLabel txtProductos;
    private javax.swing.JLabel txtTrabajadores;
    private javax.swing.JLabel txtVolverAtras;
    // End of variables declaration//GEN-END:variables
}
