
package inicializar;

import administradores.PanelPrincipalAdmin;
import conexion.ConectarBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import recepcionistas.Menu1;
import tecnicos.MenuTecnicos;

/**
 *
 * @author RUPER
 */
public class InicioSesion extends JFrame {

    /**
     * Creates new form Main
     */
    public InicioSesion() {
        initComponents();
        setTitle("FixBox");
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        usu = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        usuTxt = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(219, 219, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/logoNuevoDer.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 170, 150));

        usu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        usu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usu.setText("Usuario :");
        jPanel1.add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, 30));

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/logoNuevoIzq.png"))); // NOI18N
        jPanel1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FIXBOX");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, 80));

        pass.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pass.setText("Contraseña :");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 30));

        usuTxt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        usuTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuTxtActionPerformed(evt);
            }
        });
        jPanel1.add(usuTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 410, 40));

        btnEntrar.setBackground(new java.awt.Color(255, 51, 102));
        btnEntrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 160, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 80, 60));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 513, 580, 10));

        passTxt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 410, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 650));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/—Pngtree—hand drawn design paper page_5442781.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 580, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuTxtActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Connection cn = ConectarBD.conectar();
        boolean validador = false;
        if (usuTxt.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debes ingresar un usuario", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
        else if (passTxt.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Debes ingresar una contraseña", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
        else {
            try {
                PreparedStatement comprobarUsuario = cn.prepareStatement("SELECT USUARIO FROM TRABAJADORES WHERE USUARIO=?");
                comprobarUsuario.setString(1, usuTxt.getText());
                ResultSet rs = comprobarUsuario.executeQuery();
                if (rs.next()) {
                    validador = true;
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Hubo un error al comprobar los datos: " + e, "Mensaje de error", JOptionPane.ERROR_MESSAGE);
            }
            if (validador) {
                try {
                    PreparedStatement comprobarPass = cn.prepareStatement("SELECT PASS FROM TRABAJADORES WHERE PASS=?");
                    comprobarPass.setString(1, passTxt.getText());
                    ResultSet rs = comprobarPass.executeQuery();
                    if (rs.next()) {
                        validador = true;
                    } else {
                        validador = false;
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error al comprobar los datos: " + e, "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                }
                if (validador) {
                    try {
                        PreparedStatement comprobarAmbos = cn.prepareStatement("SELECT USUARIO, PASS FROM TRABAJADORES WHERE USUARIO = ? AND PASS=?");
                        comprobarAmbos.setString(1, usuTxt.getText());
                        comprobarAmbos.setString(2, passTxt.getText());
                        ResultSet rs = comprobarAmbos.executeQuery();
                        if (rs.next()) {
                            validador = true;
                        } else {
                            validador = false;
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Hubo un error al comprobar los datos: " + e, "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                    }
                    if (validador) {
                        String tipo="";
                        try {
                        PreparedStatement comprobarAmbos = cn.prepareStatement("SELECT TIPO FROM TRABAJADORES WHERE USUARIO = ? AND PASS=?");
                        comprobarAmbos.setString(1, usuTxt.getText());
                        comprobarAmbos.setString(2, passTxt.getText());
                        ResultSet rs = comprobarAmbos.executeQuery();
                        if (rs.next()) {
                            tipo = rs.getString(1);
                            segunTipoMet(tipo);
                        }
                        cn.close();
                        
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Hubo un error al comprobar los datos: " + e, "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                    }
                    } else {
                        JOptionPane.showMessageDialog(null, "La contraseña y usuario no coinciden.", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña no válida.", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro ningún usuario.", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void segunTipoMet(String tipo){
        switch(tipo){
            case "Tecnico":
                MenuTecnicos menu =new MenuTecnicos();
                menu.setVisible(true);
                this.dispose();
                break;
            case "Recepcionista":
                Menu1 menuRecp = new Menu1();
                menuRecp.setVisible(true);
                this.dispose();
                break;
            case "Administrador":
                PanelPrincipalAdmin paa=new PanelPrincipalAdmin();
                paa.setVisible(true);
                this.dispose();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Este usuario no tiene ningún tipo, contacte con los administradores del sitio.", "Mensaje de aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel usu;
    private javax.swing.JTextField usuTxt;
    // End of variables declaration//GEN-END:variables
}
