package recepcionistas;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import conexion.ConectarBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDate;

public class crearCliente extends javax.swing.JFrame {

    FrameCrearIncidencia inci = new FrameCrearIncidencia();

    public crearCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
  setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_volver = new javax.swing.JButton();
        btn_crearcliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        fieldnombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldapellidos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fielddni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldtelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fielddireccion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 63, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Crear cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 920, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 110));

        jPanel2.setBackground(new java.awt.Color(219, 219, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1430, 20));

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel2.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 110, 30));

        btn_crearcliente.setText("Siguiente");
        btn_crearcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearclienteMouseClicked(evt);
            }
        });
        btn_crearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearclienteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_crearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 720, 110, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 30));
        jPanel3.add(fieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apellidos");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, 30));
        jPanel3.add(fieldapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 220, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("DNI");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 200, 30));
        jPanel3.add(fielddni, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 220, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Teléfono");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 30));
        jPanel3.add(fieldtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 200, 30));
        jPanel3.add(fieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 220, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Dirección");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 200, 30));
        jPanel3.add(fielddireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 220, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 930, 290));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 20, 780));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1450, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearclienteMouseClicked
        crearCliente();
    }//GEN-LAST:event_btn_crearclienteMouseClicked

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        PanelClientes clientes = new PanelClientes();
        clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_crearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                new crearCliente().setVisible(true);
            }
        });
    }

    public void crearCliente() {
        campoNombre = fieldnombre.getText();
        campoApellidos = fieldapellidos.getText();
        campoDni = fielddni.getText();
        campoEmail = fieldemail.getText();
        campoTelefono = fieldtelefono.getText();
        campoDireccion = fielddireccion.getText();
         LocalDate fechaalta = LocalDate.now();

        try {
            Connection cn = ConectarBD.conectar();
            String sql = "INSERT INTO Clientes (Nombre, Apellidos, DNI, Correo, Telefono, Direccion, FechaRegistro) VALUES (?, ?, ?, ?, ?, ?,?)"; //ALGUNOS FALTAN EN LA BASE DE DATOS
            PreparedStatement ps = cn.prepareStatement(sql);

            ps.setString(1, campoNombre);
            ps.setString(2, campoApellidos);
            ps.setString(3, campoDni);
            ps.setString(4, campoEmail);
            ps.setString(5, campoTelefono);
            ps.setString(6, campoDireccion);
            ps.setDate(7, java.sql.Date.valueOf(fechaalta));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cliente añadido");
            inci.fielddni.setText(campoDni);
            inci.setVisible(true);
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) { // Código de error 1062 (violación de clave unica)
                JOptionPane.showMessageDialog(null, "El DNI ingresado ya existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("Error al crear el cliente: " + e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearcliente;
    private javax.swing.JButton btn_volver;
    private javax.swing.JTextField fieldapellidos;
    private javax.swing.JTextField fielddireccion;
    private javax.swing.JTextField fielddni;
    private javax.swing.JTextField fieldemail;
    public static javax.swing.JTextField fieldnombre;
    private javax.swing.JTextField fieldtelefono;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    String campoNombre;
    String campoApellidos;
    String campoDni;
    String campoDireccion;
    String campoTelefono;
    String campoEmail;
}
