package recepcionistas;

import com.formdev.flatlaf.FlatLightLaf;
import conexion.ConectarBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

public class FrameModificarClientesRecepcion extends javax.swing.JFrame {

    /**
     * Creates new form FrameModificarClientesRecepcion
     */
    public FrameModificarClientesRecepcion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contenedorMain = new javax.swing.JPanel();
        btnModificar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        txtDni = new javax.swing.JLabel();
        campoDni = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        txtEstado = new javax.swing.JLabel();
        rdActivo = new javax.swing.JRadioButton();
        rdInactivo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorMain.setBackground(new java.awt.Color(219, 219, 209));
        contenedorMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnModificar1.setText("Modificar");
        btnModificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificar1MouseClicked(evt);
            }
        });
        contenedorMain.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 780, 130, 40));

        jPanel1.setBackground(new java.awt.Color(70, 63, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Datos del cliente con ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 70));

        labelid.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        labelid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 50));

        contenedorMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 100));

        jPanel2.setBackground(new java.awt.Color(219, 219, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNombre.setText("Nombre");
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));
        jPanel2.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 30));

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtApellidos.setText("Apellidos");
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 260, 30));
        jPanel2.add(campoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 260, 30));

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDireccion.setText("Dirección");
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 260, 30));
        jPanel2.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 260, 30));

        txtDni.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDni.setText("Dni");
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 260, 30));
        jPanel2.add(campoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 260, 30));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEmail.setText("Email");
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 260, 30));
        jPanel2.add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 260, 30));

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTelefono.setText("Telefono");
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 260, 30));
        jPanel2.add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 260, 30));

        txtEstado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEstado.setText("Estado");
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 40));

        buttonGroup1.add(rdActivo);
        rdActivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rdActivo.setText("Activo");
        rdActivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdActivoItemStateChanged(evt);
            }
        });
        jPanel2.add(rdActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        buttonGroup1.add(rdInactivo);
        rdInactivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rdInactivo.setText("Inactivo");
        rdInactivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdInactivoItemStateChanged(evt);
            }
        });
        jPanel2.add(rdInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        contenedorMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1010, 340));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        contenedorMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1430, 20));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        contenedorMain.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 100, 20, 750));

        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Añadir incidencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contenedorMain.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 780, 160, 40));

        getContentPane().add(contenedorMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1446, 844));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificar1MouseClicked

        modificarCliente();
    }//GEN-LAST:event_btnModificar1MouseClicked

    private void rdActivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdActivoItemStateChanged
    
    }//GEN-LAST:event_rdActivoItemStateChanged

    private void rdInactivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdInactivoItemStateChanged
       
    }//GEN-LAST:event_rdInactivoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       FrameCrearNuevaIncidencia inci = new  FrameCrearNuevaIncidencia();
       inci.labelid.setText(this.labelid.getText());
       inci.fielddni.setText(this.campoDni.getText());
       inci.fieldnombre.setText(this.campoNombre.getText());
        inci.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameModificarClientesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameModificarClientesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameModificarClientesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameModificarClientesRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                new FrameModificarClientesRecepcion().setVisible(true);
            }
        });
    }

    public void modificarCliente() {

        try {
            int idcliente = Integer.parseInt(labelid.getText());
            String sql = "UPDATE CLIENTES SET NOMBRE=?, APELLIDOS=?, DNI=?, CORREO=?, TELEFONO=?, DIRECCION=?, ESTADOACTUAL=? WHERE ID_CLIENTES=? ";
            Connection cn = ConectarBD.conectar();
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, campoNombre.getText());
            ps.setString(2, campoApellidos.getText());
            ps.setString(3, campoDni.getText());
            ps.setString(4, campoEmail.getText());
            ps.setString(5, campoTelefono.getText());
            ps.setString(6, campoDireccion.getText());
            if(rdActivo.isSelected()){
                ps.setString(7, rdActivo.getText());
            }else{
                ps.setString(7, rdInactivo.getText());
            }
            ps.setInt(8, idcliente);

            int filas = ps.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(null, "Cliente actualizado");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }

    }

    String nombre, apellidos, dni, direccion, telefono, email, estado, id;

    public String getTelefono() {
        return telefono;
    }

    public String getId() {
        return labelid.getText();
    }

    public void setId(String id) {
        this.id = id;
        labelid.setText(id);
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
        campoTelefono.setText(telefono);
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
        campoNombre.setText(nombre);
    }

    public String getNombre(String nombre) {
        return campoNombre.getText();
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
        campoApellidos.setText(apellidos);
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
        campoDni.setText(dni);
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
        campoDireccion.setText(direccion);
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
        campoEmail.setText(email);
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
        if(estado.equalsIgnoreCase("Activo")){
            rdActivo.setSelected(true);
        }else{
            rdInactivo.setSelected(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JPanel contenedorMain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel labelid;
    private javax.swing.JRadioButton rdActivo;
    private javax.swing.JRadioButton rdInactivo;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtDni;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
