package recepcionistas;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.Timer;

public class PanelClientes extends JFrame {

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        labelbacknuevocliente.setVisible(false);
        labelbackconsultarcliente.setVisible(false);

        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              
                actualizarHora();
            }
        });
        timer.start();
    setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./iconimages/images.jpg"));
        return icono;
    }
    private void actualizarHora() {
        Locale spanish = new Locale("es", "ES");

  
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar calendario = Calendar.getInstance();
        int hora, minutos, segundos;
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);

        labelhora.setText(sdf.format(new java.util.Date()) + "  " + hora + ":" + minutos + ":" + segundos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtVolverAtras = new javax.swing.JLabel();
        txtNuevoCliente = new javax.swing.JLabel();
        txtConsultarCliente = new javax.swing.JLabel();
        btnCrearCliente = new javax.swing.JLabel();
        btnConsultarCliente = new javax.swing.JLabel();
        btnVolverAtras = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDiseñoPanelClientes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelbacknuevocliente = new javax.swing.JLabel();
        labelbackconsultarcliente = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1446, 844));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 219, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVolverAtras.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtVolverAtras.setForeground(new java.awt.Color(0, 0, 0));
        txtVolverAtras.setText("Volver Atrás");
        jPanel1.add(txtVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 760, 90, 50));

        txtNuevoCliente.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtNuevoCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNuevoCliente.setText("Nuevo Cliente");
        jPanel1.add(txtNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 140, -1));

        txtConsultarCliente.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtConsultarCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConsultarCliente.setText("Consultar Cliente");
        jPanel1.add(txtConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        btnCrearCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconnuevocliente.png"))); // NOI18N
        btnCrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearClienteMouseExited(evt);
            }
        });
        jPanel1.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconconsultarcliente.png"))); // NOI18N
        btnConsultarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarClienteMouseExited(evt);
            }
        });
        jPanel1.add(btnConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        btnVolverAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/iconatras.png"))); // NOI18N
        btnVolverAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverAtrasMouseExited(evt);
            }
        });
        jPanel1.add(btnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 80));

        jPanel2.setBackground(new java.awt.Color(70, 63, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiseñoPanelClientes.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        txtDiseñoPanelClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtDiseñoPanelClientes.setText("Panel Clientes");
        jPanel2.add(txtDiseñoPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 110));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1420, 20));

        labelbacknuevocliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbacknuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbacknuevocliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbacknuevoclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbacknuevoclienteMouseExited(evt);
            }
        });
        jPanel1.add(labelbacknuevocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 210, 200));

        labelbackconsultarcliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbackconsultarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconimages/circuloback.png"))); // NOI18N
        labelbackconsultarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbackconsultarclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbackconsultarclienteMouseExited(evt);
            }
        });
        jPanel1.add(labelbackconsultarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 220, 200));

        labelhora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 740, 210, 80));

        jPanel5.setBackground(new java.awt.Color(70, 63, 56));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(70, 63, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, 20, 730));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 110, 20, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseClicked
        FrameConsultasClientes consultas = new FrameConsultasClientes();
        consultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarClienteMouseClicked

    private void btnCrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearClienteMouseClicked
        crearCliente crearcliente = new crearCliente();
        crearcliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearClienteMouseClicked

    private void btnVolverAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseClicked
        Menu1 menu = new Menu1();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasMouseClicked

    private void labelbacknuevoclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacknuevoclienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacknuevoclienteMouseEntered

    private void labelbacknuevoclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbacknuevoclienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbacknuevoclienteMouseExited

    private void labelbackconsultarclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackconsultarclienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackconsultarclienteMouseEntered

    private void labelbackconsultarclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbackconsultarclienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelbackconsultarclienteMouseExited

    private void btnCrearClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearClienteMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelbacknuevocliente.setVisible(true);
    }//GEN-LAST:event_btnCrearClienteMouseEntered

    private void btnCrearClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearClienteMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelbacknuevocliente.setVisible(false);
    }//GEN-LAST:event_btnCrearClienteMouseExited

    private void btnConsultarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelbackconsultarcliente.setVisible(true);
    }//GEN-LAST:event_btnConsultarClienteMouseEntered

    private void btnConsultarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarClienteMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelbackconsultarcliente.setVisible(false);
    }//GEN-LAST:event_btnConsultarClienteMouseExited

    private void btnVolverAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnVolverAtrasMouseEntered

    private void btnVolverAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverAtrasMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnVolverAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 FlatLightLaf.setup();
                new PanelClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConsultarCliente;
    private javax.swing.JLabel btnCrearCliente;
    private javax.swing.JLabel btnVolverAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelbackconsultarcliente;
    private javax.swing.JLabel labelbacknuevocliente;
    private javax.swing.JLabel labelhora;
    private javax.swing.JLabel txtConsultarCliente;
    private javax.swing.JLabel txtDiseñoPanelClientes;
    private javax.swing.JLabel txtNuevoCliente;
    private javax.swing.JLabel txtVolverAtras;
    // End of variables declaration//GEN-END:variables
}
